global:
  scrape_interval: 1m
  scrape_timeout: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'job-grafana-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets: ['127.0.0.1:8008']
        labels:
          application: 'grafana-prometheus'